/**
 * The documentation index contract, expressed as data.
 *
 * Policy lives here; the mechanism lives in scripts/quality/validate-doc-index.mjs.
 *
 * The invariant:
 *
 *   every page under docs/   ⟺   linked from its folder's README.md
 *
 * An index is the one part of a documentation tree that cannot be checked by
 * reading it. A stale index does not look stale — it looks like a complete list,
 * which is precisely what makes it dangerous: a page missing from the index reads
 * as a page that does not exist, and the reader stops looking. So the index is
 * generated by nobody and enforced by this.
 *
 * README.md is an *index*, not a page. None of the page rules apply to it — no
 * frontmatter, no table of contents, no `alwaysApply`. It exists to be the thing
 * GitHub renders when someone browses into the folder.
 */

/** The documentation root. Everything below is relative to the repo root. */
export const DOCS_ROOT = "docs";

/** The repository's front page. It must lead a reader into the docs. */
export const ROOT_README = "README.md";

/** The index at the top of the documentation tree. */
export const DOCS_INDEX = "docs/README.md";

/**
 * The filename that makes a folder self-describing.
 *
 * Lowercase-then-uppercase `README.md` is the one name GitHub renders inline when
 * a folder is opened, which is the entire reason an index is worth having rather
 * than a flat file listing. It passes the doc naming rule in naming.mjs without an
 * exception being carved for it: `^[A-Z0-9]+(?:_[A-Z0-9]+)*\.md$` matches README.
 */
export const INDEX_FILE = "README.md";

/** Directories inside docs/ that hold no pages and need no index. */
export const SKIP_DIRS = new Set(["assets", "images"]);

export const DOC_INDEX = {
  id: "doc-index",

  hints: {
    missingIndex: (dir) =>
      `Create ${dir}/README.md and link every page in this folder from it.`,

    notIndexed: (index) =>
      `Add a link to this page in ${index}. An unlisted page reads as a page that does not exist.`,

    deadLink: (index) =>
      `${index} links to a file that is not there. Fix the path, or drop the line.`,

    orphanSection: (index) =>
      `${index} must link to this folder's README.md, or the section is unreachable.`,

    rootDetached: (index) =>
      `${ROOT_README} must link to ${index}. Every page back-links to the root README, so the root README has to lead somewhere.`,
  },
};
